name: Rust

on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ubt-Build
      run: cargo build --release --verbose
    #- name: Run tests
    #  run: cargo test --verbose
    - name: Upload artifact Ubt Release
      uses: actions/upload-artifact@v2
      with:
        name: Urlcode_Elf
        path: ./target/release/UrlCode
      
  build2:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: win-Build
      run: cargo build --release --verbose
    - name: Upload artifact Win Release
      uses: actions/upload-artifact@v2
      with:
        name: Urlcode_Exe
        path: ./target/release/UrlCode.exe
      
  
