name: Rust

on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Linux-Build
      run: cargo build --release --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Urlcode_Linux
        path: ./target/release/UrlCode
  
  build2:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Windows-Build
      run: cargo build --release --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Urlcode_Windows
        path: ./target/release/UrlCode
      
  
